language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DOCKER_COMPOSE_VERSION=1.24.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

services:
  - docker

install:
  - pip install -U pip
  - pip install -r requirements.txt

script:
  - python3 server.py
  - python3 test_server.py

after_success:
  - cat ~/docker_password.txt | docker login -u kirillkalmutsky --password-stdin
  - docker build -t server
  - docker images
  - docker tag server kirillkalmutsky/server
  - docker push kirillkalmutsky/server
  
